### ISSUE TITLE
Unable to access License Data

### ISSUE THREAD

**Issue by vivekmishra1991** [moses-palmer/truepy#2]
On accesing licence_data from a loaded licence , I get following error
   ` print(License.license_data)
AttributeError: type object 'License' has no attribute 'license_data'`
How to access License Data ?

**Comment by moses-palmer** [comment]
The license data can be accessed as the attribute `License.data`.

**Comment by vivekmishra1991** [comment]
`License.data` still gives me error. Its a typo it should be `license.data`.
Also how to access my data from the returned  `truepy._license_data.LicenseData object`. Can you point to some documentation or sample ?
Thanks

**Comment by moses-palmer** [comment]
I have not set up publishing of the documentation for this library, but that is obviously needed.

In order to access the extra data associated with your license, use [truepy.License.data.extra](https://github.com/moses-palmer/truepy/blob/master/lib/truepy/_license_data.py#L73).
