### ISSUE TITLE
License verified but it should be rejected.

### ISSUE THREAD

**Issue by pawisoon** [moses-palmer/truepy#4]
Hi,
I'm facing the issue where my license should be invalid but It passes the verification.
I created the cert valid 1000 days
```
openssl req -x509 \
    -newkey rsa:4096 \
    -keyout key.pem \
    -out certificate.pem \
    -days 1000
```
Then used it to issue the license as in the example  but with a date  2019-10-01T00:00:00 - 2019-12-01T00:00:00

```
from cryptography.hazmat import backends
from cryptography.hazmat.primitives import serialization

from truepy import LicenseData, License


# Load the certificate
with open('certificate.pem', 'rb') as f:
    certificate = f.read()

# Load the private key
with open('key.pem', 'rb') as f:
    key = serialization.load_pem_private_key(
        f.read(),
        password=b'MySecretPassword',
        backend=backends.default_backend())

# Issue the license
license = License.issue(
    certificate,
    key,
    license_data=LicenseData(
        '2019-10-01T00:00:00',
        '2019-12-01T00:00:00'))

# Store the license
with open('license.key', 'wb') as f:
    license.store(f, b'LicensePassword')
```

So validation should fail as its 11th of December today. 
Is my thinking correct? 
Cheers,
Pawel

**Comment by moses-palmer** [comment]
Hi,

The call to `verify` only validates the signature, not whether the license is actually valid; for this, you will have to compare the license expiry to a trusted source of the current time. The reasoning behind this is:
* You will be able to load expired licenses and retrieve meta data.
* It is out of scope for this library to provide a trusted source of the current time. When validating licenses, you may not want to trust the computer running the code.

**Comment by motein** [comment]
So what is the final solution then?

**Comment by moses-palmer** [comment]
The final solution is to check the `not_after` field of the license data after the license has been loaded.
